import type { Metadata } from 'next'
import type { ReactNode } from 'react'

import Bootstrapper from '@/store/Bootstrapper'

import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({
    children
}: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="zh-tw">
            <body>
                <Bootstrapper />
                {children}
            </body>
        </html>
    )
}
